spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ## create ## can be changed to "update" if we don't want the data to be wiped on every restart
      ddl-auto: update
    session:
      store-type: jdbc
      timeout:
        seconds: 900
      jdbc:
        initialize-schema: always

security:
  token:
    secret: ${TOKEN_SECRET}